from linked_list import *

ll1 = LinkedList()
ll1.insert_at_end(Node(1))
ll1.insert_at_end(Node(2))
ll1.insert_at_end(Node(5))
ll1.insert_at_end(Node(8))
print(ll1)
ll2 = LinkedList()
ll2.insert_at_end(Node(3))
ll2.insert_at_end(Node(4))
# ll2.insert_at_end(Node(6))
# ll2.insert_at_end(Node(7))
print(ll2)
sorted = LinkedList.merge(ll1, ll2)
print(sorted)
